---

- include_tasks: '{{ ansible_os_family }}.yml'
- include_vars: vars/trust-ip-address.yml

- name: Nginx | create ssl directory
  file:
    path: '{{ item }}'
    mode: 0755
    state: directory
  with_items:
    - /etc/nginx/ssl
    - /etc/nginx/acl
    - /var/log/nginx/access
    - /var/log/nginx/error

- name: Nginx | upload ssl certificate
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - {src: 'ssl/', dest: '/etc/nginx/ssl/' }


- name: Nginx | nginx render template
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'nginx.conf.j2',  dest: '/etc/nginx/nginx.conf' }
    - { src: 'global.variable.conf.j2',  dest: '/etc/nginx/global.variable.conf' }
    - { src: 'acl.inc.j2',  dest: '/etc/nginx/acl/acl.inc' }
  notify: restart nginx

- include_tasks: functions/nginx-site.yml
  with_items:
    - { name: 'status', template: 'status.conf.j2' }
    - { name: 'default', template: 'default.conf.j2' }

- name: Nginx | Enable service
  service:
    name: nginx
    enabled: yes