---

- name: RabbitMQ | Add RabbitMQ repository apt-key
  apt_key:
    url: "https://www.rabbitmq.com/rabbitmq-release-signing-key.asc"
    state: present

- name: RabbitMQ | Add RabbitMQ repository
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main"
    state: present

- name: RabbitMQ | Install RabbitMQ
  apt:
    name: "rabbitmq-server=3.6.15-1"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: RabbitMQ | Install rabbitmq plugins
  rabbitmq_plugin:
    names: '{{ item }}'
    state: enabled
  with_items:
    - 'rabbitmq_management'
  notify: restart rabbitmq

- include_tasks: functions/nginx-site.yml
  with_items:
    - { name: 'rabbitmq-management', template: 'rabbitmq.conf.j2' }

- name: RabbitMQ | Enable service
  service:
    name: rabbitmq-server
    enabled: yes