---

- name: create diretories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /etc/newrelic
    - /var/log/newrelic

- name: install newrelic-plugins
  pip:
    name: '{{ item }}'
    executable: 'pip2'
  with_items:
    - 'pyOpenSSL'
    - 'newrelic-plugin-agent'
#    - 'newrelic-plugin-agent[nginx]'
    - 'newrelic-plugin-agent[postgresql]'
    - 'newrelic-plugin-agent[memcached]'
#    - 'newrelic-plugin-agent[elasticsearch]'
    - 'newrelic-plugin-agent[rabbitmq]'
#    - 'newrelic-plugin-agent[uwsgi]'

- name: upload newrelic-plugins config
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'newrelic-plugin-agent.cfg.j2',     dest: '/etc/newrelic/newrelic-plugin-agent.cfg' }
    - { src: 'newrelic-plugin-agent.service.j2', dest: '/etc/systemd/system/newrelic-plugin-agent.service' }
  notify:
    - systemd-reload
    - restart newrelic-plugin-agent
