version: "2"

services:
    ansible:
        build: ansible
        privileged: true
        environment:
            - PREFIX_PATH=${SRC_PATH}
        volumes:
            - '${SRC_PATH}:/opt/ansible-configuration'
        working_dir: /opt/ansible-configuration
        command: sleep infinity

